server:
  port: 8092
spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9082/realms/spring-boot
          jwk-set-uri: http://localhost:9082/realms/spring-boot/protocol/openid-connect/certs
app:
  keycloak:
    admin:
      client-id: admin-cli
      client-secret: 1vnzZCt6TLtE1jjOvppdDsuRbLApTGb4
    user:
      client-id: spring-boot-app
    realm: spring-boot
    server-url: http://localhost:9082
    grant-type: client_credentials
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka/
    register-with-eureka: true
    fetch-registry: true
springdoc:
  api-docs:
    path: /keycloak-auth-service-docs/v3/api-docs
  swagger-ui:
    path: /keycloak-auth-service-docs/swagger-ui.html
openapi:
  service:
    title: Keycloak Auth Service Docs
    version: 1.0.0
    url: ${OPENAPI_SERVICE_URL:http://localhost:8092}