apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service-deployment
  labels:
    app: library-service
spec:
  selector:
    matchLabels:
      app: library-service
  template:
    metadata:
      labels:
        app: library-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z postgres-library-service 5432; do echo waiting for postgres; sleep 2; done;' ]
        - name: wait-for-eureka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z eureka-service 8093; do echo waiting for eureka; sleep 2; done;' ]
        - name: wait-for-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z kafka-cluster-kafka-bootstrap 9092; do echo waiting for kafka; sleep 2; done;' ]
      containers:
        - name: library-service
          image: nixn/library-service:latest
          ports:
            - containerPort: 8062
          envFrom:
            - configMapRef:
                name: library-config
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: LoadBalancer
  ports:
    - port: 8062
  selector:
    app: library-service