spring:
  config:
    activate:
      on-profile: integration-test
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${wiremock.port}/realms/spring-boot/protocol/openid-connect/certs
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
    consumer:
      group-id: library_group
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
eureka:
  client:
    enabled: false
springdoc:
  api-docs:
    path: /book-service-docs/v3/api-docs
  swagger-ui:
    path: /book-service-docs/swagger-ui.html
openapi:
  service:
    title: Book Service Docs
    version: 1.0.0
    url: http://localhost:8063
management:
  tracing:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false
  endpoint:
    loggers:
      enabled: false
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
keycloak:
  integration-test:
    user-jwt: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJfelZZM0oyQUg1R092dXF5eF9Qc3QxdWdaTW42NjYzbHhFNHBEdGtPWFlJIn0.eyJleHAiOjI1OTIxNDA3MTAsImlhdCI6MTcyODE0MDcxMCwianRpIjoiMjNmNmRjYmYtMjUwYi00ZWU0LTgzODMtMWE0M2UwNTY2MTY1IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDgyL3JlYWxtcy9zcHJpbmctYm9vdCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmMzc3ZTRlOC05ZjdiLTRlMDItOTQ4Ny0zNWQ1YzQyMmE1ZDEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzcHJpbmctYm9vdC1hcHAiLCJzaWQiOiI4NDc5NDFhYi05ODRmLTQwMTctOTA1Yi0wYzJlOTljZDg5N2QiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiVVNFUiIsImRlZmF1bHQtcm9sZXMtc3ByaW5nLWJvb3QiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6InVzZXIgdXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXIiLCJnaXZlbl9uYW1lIjoidXNlciIsImZhbWlseV9uYW1lIjoidXNlciIsImVtYWlsIjoidXNlckBnbWFpbC5jb20ifQ.TiJ8JWfS4FW0FkkZYC_1TgpzNP7gbEJElbnfT9LvAyG3CnbGQpWLkhMLoVajATJ56GrRK8PdGrcei-ImMxENLBZPUtPiv6In90JpoCo_j44uheL5bSF8sno6k2y8bOqbxpk6xPy4gCK7oLbmR3hc7cRrqYBMOPzSoiZca6ZY3QcaT4erFaHvPrNvlbKa05BsNLUAhwkgxxlEtk-RAUhVSVTCsMMuscbKkyTW6Vo1CXqaAHTJjb7vnlmhLHEsZvAyDIw0RlReLtK-gMI4wnvo6amG3jF2creMtgyR91SqFPJDQIKZGmxwfCju-UsR0cqe3qT9pVxK2n3cVO5FbPImaA
    admin-jwt: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJfelZZM0oyQUg1R092dXF5eF9Qc3QxdWdaTW42NjYzbHhFNHBEdGtPWFlJIn0.eyJleHAiOjI1OTIxNDA2NzMsImlhdCI6MTcyODE0MDY3MywianRpIjoiZmI4YjAwYjItYTJkMy00YjkyLThjNDYtMmRjOWRjYzEyODBiIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDgyL3JlYWxtcy9zcHJpbmctYm9vdCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIxNmQyNWI2OS02NDRkLTRlYjItYmQyNi01ODJhOTg0YjJkZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzcHJpbmctYm9vdC1hcHAiLCJzaWQiOiIxYmM4MzYyZS1hZmUzLTQ4NzctODFlNy1kODhlNjY4NTdiZjIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsIkFETUlOIiwidW1hX2F1dGhvcml6YXRpb24iLCJVU0VSIiwiZGVmYXVsdC1yb2xlcy1zcHJpbmctYm9vdCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiYWRtaW4gYWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJhZG1pbiIsImZhbWlseV9uYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9.IryACVXODIorMBO7814kPn9HMtPun2Ildvofn0rGiGcpH56dDRiJ5xF7R9T7-qnGNIbrnaC1hyTKnCTeVMT4koI_t3pxklDjHx7sNj9W9wGgoR3CMqic4EOw5ZBipCU6yMX1tpO9KYBzECEGUNuiLMrz4YT5jgt-u7czrpD7jkSOYenC4EYge_Ze7t4hUVXeib37JUF2erHFUeK_FCfQKVLdeXSFCFLKQxrIobXNswddRUsbvXqYim66LfUURbG9uOiuCwIRJh5H9Vk6YcNxsS6NCihcsz1ounN1qDbQJ36UulLO92kFYtdiU4qJCPHIJ2lLQauf5iO2R4WAiXpRXQ

wiremock:
  port: 39151