server:
  port: 8062
spring:
  config:
    activate:
      on-profile: unit-test
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-test.xml
    drop-first: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
