apiVersion: v1
kind: ConfigMap
metadata:
  name: book-config
data:
  SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:9082/realms/spring-boot"
  SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:9082/realms/spring-boot/protocol/openid-connect/certs"
  POSTGRES_HOST: "postgres-book-service:5432"
  POSTGRES_DB_NAME: "bookdb"
  POSTGRES_USERNAME: "admin"
  POSTGRES_PASSWORD: "root"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap:9092"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-service:8093/eureka"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  CLOUD_CONFIG_URI: "http://config-service:8099"