server:
  port: 8091
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka/
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true