services:
  postgres-book-service:
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookdb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  postgres-library-service:
    image: postgres:16.4
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-library-service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: librarydb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    restart: always
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NODE_ID: 1
      CLUSTER_ID: vklMNUDrTDajTTAWfP8EUA
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    labels:
      amplicode.image: confluent/kafka
  kafkaui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: always
    ports:
      - "8989:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: vklMNUDrTDajTTAWfP8EUA
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
  kc-postgres:
    image: postgres:16.4
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - kc-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    restart: always
    command: start-dev --import-realm --health-enabled=true
    volumes:
      - ./../keycloak:/opt/keycloak/data/import
    ports:
      - "9082:9082"
    environment:
      KC_HTTP_PORT: 9082
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: kc-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: root
      KC_HEALTH_ENABLED: true
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    healthcheck:
      test:
        [ "CMD-SHELL", "{ exec 3<>/dev/tcp/localhost/9000 && echo -e \"GET /health/ready HTTP/1.1\nhost: localhost:9000\n\" >&3 && timeout --preserve-status 1 cat <&3 | grep -m 1 -q 'status.*UP'; }" ]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 20
    depends_on:
      - kc-postgres

  # keycloak-init service initializes Keycloak users using a script.
  # The service will not restart after execution (restart: "no").
  # It depends on the Keycloak service being healthy before running.
  # YOU CAN REMOVE THIS CONTAINER IT AFTER FIRST START
  keycloak-init:
    image: curlimages/curl:latest
    restart: "no"
    volumes:
      - ./../keycloak/init_example_users.sh:/init_example_users.sh
    entrypoint: [ "sh", "/init_example_users.sh" ]
    depends_on:
      keycloak:
        condition: service_healthy
  book-service:
    image: book-service:latest
    build:
      context: ../book-service
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8063:8063"
    depends_on:
      - postgres-book-service
      - kafka
      - keycloak-init
    env_file: ../book-service/example.env
  library-service:
    image: library-service:latest
    build:
      context: ../library-service
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8062:8062"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8062/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - postgres-library-service
      - kafka
      - keycloak-init
    env_file: ../library-service/example.env
  eureka-service:
    image: eureka-service:latest
    build:
      context: ../eureka-service
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8093:8093"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8093/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    env_file: ../eureka-service/example.env
  keycloak-auth-service:
    image: keycloak-auth-service:latest
    build:
      context: ../keycloak-auth-service
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8092:8092"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8092/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - keycloak
    env_file: ../keycloak-auth-service/example.env
  gateway-service:
    image: gateway-service:latest
    build:
      context: ../gateway-service
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8091:8091"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8091/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - eureka-service
      - library-service
      - book-service
      - keycloak-auth-service
    env_file: ../gateway-service/example.env

volumes:
  postgres_data:
  postgres-library-service_data:
  kafka_data:
  kc-postgres_data: