server:
  port: 8061
spring:
  application:
    name: book-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    consumer:
      group-id: library_group
    bootstrap-servers: localhost:9092
springdoc:
  swagger-ui:
    enabled: true