server:
  port: 8063
spring:
  application:
    name: book-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/spring-boot}
          jwk-set-uri: ${SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:9082/realms/spring-boot/protocol/openid-connect/certs}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    consumer:
      group-id: library_group
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /book-service-docs/v3/api-docs
  swagger-ui:
    path: /book-service-docs/swagger-ui.html
openapi:
  service:
    title: Book Service Docs
    version: 1.0.0
    url: ${OPENAPI_SERVICE_URL:http://localhost:8063}