apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z otel-collector 4317; do echo waiting for eureka; sleep 2; done;' ]
      containers:
        - name: config-service
          image: nixn/config-service:latest
          ports:
            - containerPort: 8099
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort
  ports:
    - port: 8099
  selector:
    app: config-service