apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686 # Jaeger UI
              name: ui
            - containerPort: 4317   # OTLP gRPC receiver
              name: grpc
          # Optional: set a health check for the Jaeger service
          readinessProbe:
            httpGet:
              path: /health
              port: 16686
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: LoadBalancer
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: ui
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc
  selector:
    app: jaeger