apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://localhost:8093/eureka"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  CLOUD_CONFIG_URI: "http://config-service:8099"