apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:9082/realms/spring-boot"
  SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:9082/realms/spring-boot/protocol/openid-connect/certs"
  APP_KEYCLOAK_ADMIN_CLIENT_ID: "admin-cli"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-service:8093/eureka"
  APP_KEYCLOAK_ADMIN_CLIENT_SECRET: "1vnzZCt6TLtE1jjOvppdDsuRbLApTGb4"
  APP_KEYCLOAK_USER_CLIENT_ID: "spring-boot-app"
  APP_KEYCLOAK_REALM: "spring-boot"
  APP_KEYCLOAK_SERVER_URL: "http://keycloak:9082"
  APP_KEYCLOAK_GRANT_TYPE: "client_credentials"
  CLOUD_CONFIG_URI: "http://config-service:8099"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"