apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-auth-service-deployment
  labels:
    app: keycloak-auth-service
spec:
  selector:
    matchLabels:
      app: keycloak-auth-service
  template:
    metadata:
      labels:
        app: keycloak-auth-service
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z eureka-service 8093; do echo waiting for eureka; sleep 2; done;' ]
        - name: wait-for-keycloak
          image: busybox
          command: [ 'sh', '-c', 'until nc -z keycloak 9082; do echo waiting for keycloak; sleep 2; done;' ]
      containers:
        - name: keycloak-auth-service
          image: nixn/keycloak-auth-service:latest
          ports:
            - containerPort: 8092
          envFrom:
            - configMapRef:
                name: keycloak-config
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-auth-service
spec:
  type: LoadBalancer
  ports:
    - port: 8092
  selector:
    app: keycloak-auth-service