apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-auth-service-deployment
  labels:
    app: keycloak-auth-service
spec:
  selector:
    matchLabels:
      app: keycloak-auth-service
  template:
    metadata:
      labels:
        app: keycloak-auth-service
    spec:
      containers:
        - name: keycloak-auth-service
          image: nixn/keycloak-auth-service:latest
          ports:
            - containerPort: 8092
          envFrom:
            - configMapRef:
                name: keycloak-config
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-auth-service
spec:
  type: NodePort
  ports:
    - port: 8092
  selector:
    app: keycloak-auth-service